# Generated by Django 3.1.7 on 2021-03-21 01:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210321_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20, null=True), null=True, size=None),
        ),
        migrations.AddField(
            model_name='user',
            name='watched_anime',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, null=True), null=True, size=None),
        ),
    ]
